Update md-file-check.yml

diff --git a/.github/workflows/md-file-check.yml b/.github/workflows/md-file-check.yml
--- a/.github/workflows/md-file-check.yml
+++ b/.github/workflows/md-file-check.yml
@@ -9,11 +9,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Set up Git
+        run: |
+          git config --global user.email "you@example.com"
+          git config --global user.name "Your Name"
+
       - name: Check for non-Markdown file changes
         id: check_files
         run: |
+          # Get the base and head SHA
+          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
+            BASE_SHA=$(jq -r .pull_request.base.sha "$GITHUB_EVENT_PATH")
+            HEAD_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
+          else
+            BASE_SHA=$(git rev-parse HEAD^1)
+            HEAD_SHA=$(git rev-parse HEAD)
+          fi
+
           # Get a list of files changed in the pull request
-          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
+          CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
 
           # Initialize a flag to false
           NON_MARKDOWN_CHANGED=false
@@ -30,12 +44,10 @@ jobs:
           # Export the result
           echo "::set-output name=non_markdown_changed::$NON_MARKDOWN_CHANGED"
 
-      - name: Fail if non-Markdown files are changed
-        if: steps.check_files.outputs.non_markdown_changed == 'true'
+      - name: Set status based on file changes
         run: |
-          echo "Non-Markdown files have changed. Failing the check."
-          exit 1
-
-      - name: Success if only Markdown files are changed
-        if: steps.check_files.outputs.non_markdown_changed == 'false'
-        run: echo "Only Markdown files have changed. Check passed."
+          if [ "${{ steps.check_files.outputs.non_markdown_changed }}" == "true" ]; then
+            echo "Non-Markdown files have changed. Failing the check."
+            exit 1
+          else
+            echo "Only Markdown files have changed. Check passed."
